name: 'Code style'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    uses: technology-studio/github-workflows/.github/workflows/_code-style.yml@main
