name: 'Code style'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
      - run: yarn lint
