name: "PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Ensure semantic PR title
    runs-on: ubuntu-latest
    steps:
      - uses: technology-studio/github-workflows/.github/workflows/_pr.yml@main
