name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: technology-studio/github-workflows/.github/workflows/_release.yml@main
